### ISSUE TITLE
Highscore signs

### ISSUE THREAD

**Issue by IgnasJJK** [rangewonk/LonksKits#13]
Sometimes, signs get stuck and have to be replaced.

**Comment by rangewonk** [comment]
I thought this was fixed, however this bug happened again last night.  To create a sign I must write on the first line  [hs]   and on the second line the number. 1,2,3 etc.
Would it be possible instead of me having to re-make 10 signs to make a command which reloads / re-builds the signs?

**Comment by IgnasJJK** [comment]
The async tasks might be interfering with themselves, because they are run every second. Maybe the refresh time should be increased?

**Comment by IgnasJJK** [comment]
Destroyed highscore signs don't get removed from Signs.yml

**Comment by IgnasJJK** [comment]
I have replaced the highscore sign system with one that seems to work reliably.
The signs now get saved in the signs.yml file with unique ids.
The signs get removed from the signs.yml file when destroyed.
The signs now get the scores straight from the score cache.
The signs get updated every 5 seconds.
Any signs for positions other that 1-10 will work.
