### ISSUE TITLE
Color Scoreboard

### ISSUE THREAD

**Issue by rangewonk** [rangewonk/LonksKits#14]
If a player has a really long name, their name on the scoreboard is black;not blue. Maxon said this is because their name is to long to fit with the color code. Is there a way around this to make it fit with color or is there no way whatsoever?

**Comment by IgnasJJK** [comment]
I've seen a plugin that allows longer text on signs. I'll look into it tommorrow.

**Comment by IgnasJJK** [comment]
Didn't find it. The length of a sign's lines cannot be changed, so there isn't an easy way to show the entire name on the sign.

**Comment by rangewonk** [comment]
I believe they are extending the amount of characters on signs once the server is fully updated to 1.8. Hopefully this will fix the issue.
