### ISSUE TITLE
Block Damage

### ISSUE THREAD

**Issue by rangewonk** [rangewonk/LonksKits#17]
As players can break blocks and run through them before they respawn if they are 1x1 blocks, you said you would try and deny all block damage in the kitpvp world unless the player is on /build bypass mode.

**Comment by IgnasJJK** [comment]
if the BlockDamageEvent was cancelled on the kitpvp world, the blocks would be impossible to damage, therefore would never be broken.

**Comment by IgnasJJK** [comment]
Cancellation of the BlockDamageEvent doesn't seem to prevent players from damaging blocks.
