### ISSUE TITLE
Highscores recently online players

### ISSUE THREAD

**Issue by rangewonk** [rangewonk/LonksKits#18]
Some of the players on the Highscores haven't been online on Lonks in months. Though I do not want to reset their points, would it be possible to hide players from the highscores that haven't been online in X amount of time?

**Comment by IgnasJJK** [comment]
Not unless there's a way to get the amount of time they have been offline for.

**Comment by rangewonk** [comment]
well I have an /ontime plugin which tracks how long they have been online,  and the /seen command which is linked in with essentials which shows how long ago they were online.

**Comment by IgnasJJK** [comment]
If the people with more than 0 points were excluded from the list, some people would see the wrong rank position with the /points command, because some players would be unaccounted for.
